// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTAPIProject.Data.ApplicationDbContext;

#nullable disable

namespace RESTAPIProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTAPIProject.Models.Villa.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<int?>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(8883),
                            Details = "SXX XAXIBYJUZYEZCU",
                            ImageUrl = "",
                            Name = "QIJGLDY Villa",
                            Occupancy = 60,
                            Rate = 888.83000000000004,
                            Sqft = 3616
                        },
                        new
                        {
                            Id = -2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9023),
                            Details = "NBORW ODYOV",
                            ImageUrl = "",
                            Name = "REW Villa",
                            Occupancy = 28,
                            Rate = 773.17999999999995,
                            Sqft = 29141
                        },
                        new
                        {
                            Id = -3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9039),
                            Details = "PUVBKVSSRFBXSZH ",
                            ImageUrl = "",
                            Name = "GL Villa",
                            Occupancy = 76,
                            Rate = 695.66999999999996,
                            Sqft = 26020
                        },
                        new
                        {
                            Id = -4,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9053),
                            Details = "ZYRAFJEDLTO",
                            ImageUrl = "",
                            Name = "RARINBN Villa",
                            Occupancy = 45,
                            Rate = 401.43000000000001,
                            Sqft = 3701
                        },
                        new
                        {
                            Id = -5,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9067),
                            Details = "VHSJGPKILKGXFD",
                            ImageUrl = "",
                            Name = "RW Villa",
                            Occupancy = 97,
                            Rate = 241.36000000000001,
                            Sqft = 22829
                        },
                        new
                        {
                            Id = -6,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9084),
                            Details = "NXXPFMFOKRSXFXWTJ ",
                            ImageUrl = "",
                            Name = "FNPY Villa",
                            Occupancy = 22,
                            Rate = 192.08000000000001,
                            Sqft = 16378
                        },
                        new
                        {
                            Id = -7,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9100),
                            Details = "VJEU   ZIPPIFBH",
                            ImageUrl = "",
                            Name = "EFRRKFT Villa",
                            Occupancy = 78,
                            Rate = 190.24000000000001,
                            Sqft = 9636
                        },
                        new
                        {
                            Id = -8,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9113),
                            Details = "WDGAQRQFGGX",
                            ImageUrl = "",
                            Name = "NON Villa",
                            Occupancy = 84,
                            Rate = 865.83000000000004,
                            Sqft = 23948
                        },
                        new
                        {
                            Id = -9,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9131),
                            Details = "CHKEEKLOCM QRARSYDI",
                            ImageUrl = "",
                            Name = "DQXHZTS Villa",
                            Occupancy = 46,
                            Rate = 751.53999999999996,
                            Sqft = 30529
                        },
                        new
                        {
                            Id = -10,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9146),
                            Details = "EXYJQXEGTXOFIPZEF",
                            ImageUrl = "",
                            Name = "SLK Villa",
                            Occupancy = 90,
                            Rate = 562.13999999999999,
                            Sqft = 28912
                        },
                        new
                        {
                            Id = -11,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9161),
                            Details = "RSFN KPHFJAIUOPQ",
                            ImageUrl = "",
                            Name = "XKIK Villa",
                            Occupancy = 48,
                            Rate = 962.12,
                            Sqft = 863
                        },
                        new
                        {
                            Id = -12,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9201),
                            Details = "XCQDRME FJOWLVCVX",
                            ImageUrl = "",
                            Name = "YUXT Villa",
                            Occupancy = 35,
                            Rate = 594.95000000000005,
                            Sqft = 31424
                        },
                        new
                        {
                            Id = -13,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9216),
                            Details = "HMV WMKBLCMKL",
                            ImageUrl = "",
                            Name = "NTOCX Villa",
                            Occupancy = 99,
                            Rate = 910.73000000000002,
                            Sqft = 49202
                        },
                        new
                        {
                            Id = -14,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9231),
                            Details = "JKCGWVMPFSIOZZL",
                            ImageUrl = "",
                            Name = "XTORA Villa",
                            Occupancy = 32,
                            Rate = 164.88999999999999,
                            Sqft = 30250
                        },
                        new
                        {
                            Id = -15,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9244),
                            Details = "ZNMGASUMPFX",
                            ImageUrl = "",
                            Name = "MVFMR Villa",
                            Occupancy = 24,
                            Rate = 209.66,
                            Sqft = 11803
                        },
                        new
                        {
                            Id = -16,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9256),
                            Details = "YHRXOYAIWOE",
                            ImageUrl = "",
                            Name = "CDM Villa",
                            Occupancy = 16,
                            Rate = 390.26999999999998,
                            Sqft = 26195
                        },
                        new
                        {
                            Id = -17,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9270),
                            Details = "WUFBVGMKMHOJOLR",
                            ImageUrl = "",
                            Name = "YIDMFX Villa",
                            Occupancy = 90,
                            Rate = 633.91999999999996,
                            Sqft = 6253
                        },
                        new
                        {
                            Id = -18,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9284),
                            Details = "MGC LHBEPENNL",
                            ImageUrl = "",
                            Name = "HA Villa",
                            Occupancy = 90,
                            Rate = 222.38,
                            Sqft = 18539
                        },
                        new
                        {
                            Id = -19,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9300),
                            Details = "SXHBHFOXROICFP",
                            ImageUrl = "",
                            Name = "NEYNTI Villa",
                            Occupancy = 73,
                            Rate = 317.55000000000001,
                            Sqft = 46774
                        },
                        new
                        {
                            Id = -20,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9315),
                            Details = "WAHCVATZ XWOAOUG",
                            ImageUrl = "",
                            Name = "XQSJCD Villa",
                            Occupancy = 62,
                            Rate = 786.66999999999996,
                            Sqft = 6496
                        },
                        new
                        {
                            Id = -21,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9329),
                            Details = "LRZEGDHVTJRB",
                            ImageUrl = "",
                            Name = "QJKQRK Villa",
                            Occupancy = 86,
                            Rate = 786.94000000000005,
                            Sqft = 30836
                        },
                        new
                        {
                            Id = -22,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9342),
                            Details = "SODMZVONKFQE",
                            ImageUrl = "",
                            Name = "JVO Villa",
                            Occupancy = 93,
                            Rate = 494.16000000000003,
                            Sqft = 49399
                        },
                        new
                        {
                            Id = -23,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9372),
                            Details = "GUIWCUXZHFYFHUZ UQC",
                            ImageUrl = "",
                            Name = "LN Villa",
                            Occupancy = 30,
                            Rate = 816.67999999999995,
                            Sqft = 43259
                        },
                        new
                        {
                            Id = -24,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9387),
                            Details = "VXKDGOPQCNUANXVJRMB",
                            ImageUrl = "",
                            Name = "MXLA Villa",
                            Occupancy = 78,
                            Rate = 844.65999999999997,
                            Sqft = 2388
                        },
                        new
                        {
                            Id = -25,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9400),
                            Details = "RQZH CAIXAA",
                            ImageUrl = "",
                            Name = "RZSYMZZ Villa",
                            Occupancy = 56,
                            Rate = 482.94,
                            Sqft = 9008
                        },
                        new
                        {
                            Id = -26,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9416),
                            Details = "NCQUUXHPRIXP EDU",
                            ImageUrl = "",
                            Name = "KACZV Villa",
                            Occupancy = 26,
                            Rate = 878.86000000000001,
                            Sqft = 11301
                        },
                        new
                        {
                            Id = -27,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9431),
                            Details = "X OENFVVJHVYTKICRG",
                            ImageUrl = "",
                            Name = "LXED Villa",
                            Occupancy = 83,
                            Rate = 361.60000000000002,
                            Sqft = 38682
                        },
                        new
                        {
                            Id = -28,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9446),
                            Details = "TAIQNKVCESSRNE",
                            ImageUrl = "",
                            Name = "XDUVBHA Villa",
                            Occupancy = 92,
                            Rate = 822.82000000000005,
                            Sqft = 46358
                        },
                        new
                        {
                            Id = -29,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9461),
                            Details = "TYBPCCNYWMNWWGPMIT",
                            ImageUrl = "",
                            Name = "AKWP Villa",
                            Occupancy = 14,
                            Rate = 124.67,
                            Sqft = 32869
                        },
                        new
                        {
                            Id = -30,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9474),
                            Details = "EIEDJVZIXCW",
                            ImageUrl = "",
                            Name = "NICL Villa",
                            Occupancy = 5,
                            Rate = 362.58999999999997,
                            Sqft = 30154
                        },
                        new
                        {
                            Id = -31,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9487),
                            Details = "FBZOHZFCPCUATGI",
                            ImageUrl = "",
                            Name = "UTX Villa",
                            Occupancy = 11,
                            Rate = 655.45000000000005,
                            Sqft = 31277
                        },
                        new
                        {
                            Id = -32,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9498),
                            Details = "OHMRNGGR JB",
                            ImageUrl = "",
                            Name = "SNBE Villa",
                            Occupancy = 56,
                            Rate = 549.66999999999996,
                            Sqft = 33065
                        },
                        new
                        {
                            Id = -33,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9515),
                            Details = "OTLKQBCAJGNAAVWFYAC",
                            ImageUrl = "",
                            Name = "TDTLI Villa",
                            Occupancy = 44,
                            Rate = 396.47000000000003,
                            Sqft = 15077
                        },
                        new
                        {
                            Id = -34,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9586),
                            Details = "ZECRUV W ZUP",
                            ImageUrl = "",
                            Name = "FBMBX Villa",
                            Occupancy = 37,
                            Rate = 125.81999999999999,
                            Sqft = 41530
                        },
                        new
                        {
                            Id = -35,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9602),
                            Details = "OCXMEFCPXVCSRSZXG",
                            ImageUrl = "",
                            Name = "TCDCWKO Villa",
                            Occupancy = 58,
                            Rate = 842.26999999999998,
                            Sqft = 5030
                        },
                        new
                        {
                            Id = -36,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9619),
                            Details = "MVHDJRRUWDBWQNOJQ",
                            ImageUrl = "",
                            Name = "HXXMEPZ Villa",
                            Occupancy = 51,
                            Rate = 789.70000000000005,
                            Sqft = 7688
                        },
                        new
                        {
                            Id = -37,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9635),
                            Details = "CYSMUJ FOQRTAY QRA",
                            ImageUrl = "",
                            Name = "LXWBAW Villa",
                            Occupancy = 72,
                            Rate = 349.74000000000001,
                            Sqft = 15365
                        },
                        new
                        {
                            Id = -38,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9650),
                            Details = "ISIVMGGCDMDVWUNSFG",
                            ImageUrl = "",
                            Name = "XRZ Villa",
                            Occupancy = 33,
                            Rate = 343.17000000000002,
                            Sqft = 26048
                        },
                        new
                        {
                            Id = -39,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9664),
                            Details = "TC NOUEWBG MSRAG",
                            ImageUrl = "",
                            Name = "BCH Villa",
                            Occupancy = 4,
                            Rate = 431.91000000000003,
                            Sqft = 11586
                        },
                        new
                        {
                            Id = -40,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9675),
                            Details = "ZZNDWZDYHO",
                            ImageUrl = "",
                            Name = "AV Villa",
                            Occupancy = 51,
                            Rate = 571.33000000000004,
                            Sqft = 37634
                        },
                        new
                        {
                            Id = -41,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9691),
                            Details = "IRJBKALHPZUIRHVGIOQ",
                            ImageUrl = "",
                            Name = "PQBNEK Villa",
                            Occupancy = 28,
                            Rate = 492.14999999999998,
                            Sqft = 26085
                        },
                        new
                        {
                            Id = -42,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9704),
                            Details = "QQYKJIRH S LN",
                            ImageUrl = "",
                            Name = "YYR Villa",
                            Occupancy = 59,
                            Rate = 684.61000000000001,
                            Sqft = 22074
                        },
                        new
                        {
                            Id = -43,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9719),
                            Details = "VTN WYEKVPPLJRVW",
                            ImageUrl = "",
                            Name = "NFDTMU Villa",
                            Occupancy = 56,
                            Rate = 725.14999999999998,
                            Sqft = 4683
                        },
                        new
                        {
                            Id = -44,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9732),
                            Details = "UZSQWLGYCKE",
                            ImageUrl = "",
                            Name = "PDSJM Villa",
                            Occupancy = 95,
                            Rate = 713.91999999999996,
                            Sqft = 45834
                        },
                        new
                        {
                            Id = -45,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9783),
                            Details = "PNALABFLQVUBBKVLNS",
                            ImageUrl = "",
                            Name = "FWDK Villa",
                            Occupancy = 2,
                            Rate = 489.77999999999997,
                            Sqft = 36058
                        },
                        new
                        {
                            Id = -46,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9793),
                            Details = "GZUUY SRTX",
                            ImageUrl = "",
                            Name = "UK Villa",
                            Occupancy = 78,
                            Rate = 154.74000000000001,
                            Sqft = 35523
                        },
                        new
                        {
                            Id = -47,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9806),
                            Details = "FUSRUQGYAOGFY",
                            ImageUrl = "",
                            Name = "KW Villa",
                            Occupancy = 12,
                            Rate = 144.71000000000001,
                            Sqft = 37953
                        },
                        new
                        {
                            Id = -48,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9819),
                            Details = " CLEKKEESIZMWZ",
                            ImageUrl = "",
                            Name = "QD Villa",
                            Occupancy = 4,
                            Rate = 563.32000000000005,
                            Sqft = 13495
                        },
                        new
                        {
                            Id = -49,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9833),
                            Details = "ZLRAUXCVNUHR",
                            ImageUrl = "",
                            Name = "RMSFR Villa",
                            Occupancy = 58,
                            Rate = 598.25,
                            Sqft = 36861
                        },
                        new
                        {
                            Id = -50,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9844),
                            Details = "MJRZKGKS WCF",
                            ImageUrl = "",
                            Name = "CH Villa",
                            Occupancy = 73,
                            Rate = 234.30000000000001,
                            Sqft = 7401
                        },
                        new
                        {
                            Id = -51,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9857),
                            Details = "MBIGNHTWGZOYMRH",
                            ImageUrl = "",
                            Name = "GXP Villa",
                            Occupancy = 44,
                            Rate = 557.35000000000002,
                            Sqft = 29287
                        },
                        new
                        {
                            Id = -52,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9873),
                            Details = "MUUNRIECSIC OWKLTO",
                            ImageUrl = "",
                            Name = "OBMWY Villa",
                            Occupancy = 64,
                            Rate = 443.05000000000001,
                            Sqft = 43781
                        },
                        new
                        {
                            Id = -53,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9885),
                            Details = "HM NLONIYODBXDJ",
                            ImageUrl = "",
                            Name = "ID Villa",
                            Occupancy = 90,
                            Rate = 945.90999999999997,
                            Sqft = 7094
                        },
                        new
                        {
                            Id = -54,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9898),
                            Details = "XQHUJWN JYMIEC",
                            ImageUrl = "",
                            Name = "LUYB Villa",
                            Occupancy = 51,
                            Rate = 872.19000000000005,
                            Sqft = 20385
                        },
                        new
                        {
                            Id = -55,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9915),
                            Details = "XMYASITMTTQIVJBPCF",
                            ImageUrl = "",
                            Name = "MSCWOJM Villa",
                            Occupancy = 41,
                            Rate = 933.62,
                            Sqft = 25904
                        },
                        new
                        {
                            Id = -56,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9930),
                            Details = "JTONNHWXRCUUWFSGUL",
                            ImageUrl = "",
                            Name = "FPK Villa",
                            Occupancy = 23,
                            Rate = 469.01999999999998,
                            Sqft = 47190
                        },
                        new
                        {
                            Id = -57,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9970),
                            Details = "XSVUFA TIJKCXOLTFAN",
                            ImageUrl = "",
                            Name = "AENDKT Villa",
                            Occupancy = 54,
                            Rate = 181.08000000000001,
                            Sqft = 22608
                        },
                        new
                        {
                            Id = -58,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 932, DateTimeKind.Local).AddTicks(9985),
                            Details = "USAPMUCLWTZMXNXNM",
                            ImageUrl = "",
                            Name = "RQIG Villa",
                            Occupancy = 75,
                            Rate = 240.22,
                            Sqft = 22908
                        },
                        new
                        {
                            Id = -59,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(3),
                            Details = "FJNRMVASZWZJEVLUWRF",
                            ImageUrl = "",
                            Name = "YIHJRKN Villa",
                            Occupancy = 68,
                            Rate = 247.91,
                            Sqft = 35138
                        },
                        new
                        {
                            Id = -60,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(16),
                            Details = "XIMPWKWGDZZQV",
                            ImageUrl = "",
                            Name = "QCOT Villa",
                            Occupancy = 53,
                            Rate = 307.77999999999997,
                            Sqft = 41102
                        },
                        new
                        {
                            Id = -61,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(32),
                            Details = "BMA WQJULJJSJJKIW ",
                            ImageUrl = "",
                            Name = "BFAOA Villa",
                            Occupancy = 99,
                            Rate = 230.25999999999999,
                            Sqft = 32451
                        },
                        new
                        {
                            Id = -62,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(45),
                            Details = "XYOPQMEAHYPRKT",
                            ImageUrl = "",
                            Name = "GA Villa",
                            Occupancy = 66,
                            Rate = 609.10000000000002,
                            Sqft = 12176
                        },
                        new
                        {
                            Id = -63,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(60),
                            Details = "BTFOMO ATQSMJNFB",
                            ImageUrl = "",
                            Name = "ZOPBGWH Villa",
                            Occupancy = 90,
                            Rate = 884.96000000000004,
                            Sqft = 7658
                        },
                        new
                        {
                            Id = -64,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(74),
                            Details = "VIH NUVKJYBNBJSQBR",
                            ImageUrl = "",
                            Name = "LIA Villa",
                            Occupancy = 34,
                            Rate = 804.15999999999997,
                            Sqft = 47341
                        },
                        new
                        {
                            Id = -65,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(89),
                            Details = "IH RNJQLFRD BCKDO",
                            ImageUrl = "",
                            Name = "KNXFP Villa",
                            Occupancy = 97,
                            Rate = 475.73000000000002,
                            Sqft = 1534
                        },
                        new
                        {
                            Id = -66,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(126),
                            Details = "ZJFAVRS IMX HT",
                            ImageUrl = "",
                            Name = "RR Villa",
                            Occupancy = 71,
                            Rate = 289.67000000000002,
                            Sqft = 2820
                        },
                        new
                        {
                            Id = -67,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(141),
                            Details = "FMIIQZPPCF EHY",
                            ImageUrl = "",
                            Name = "XEAA Villa",
                            Occupancy = 15,
                            Rate = 687.36000000000001,
                            Sqft = 36897
                        },
                        new
                        {
                            Id = -68,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(156),
                            Details = "CGOZG  PVJNMNM",
                            ImageUrl = "",
                            Name = "LKUYOWN Villa",
                            Occupancy = 23,
                            Rate = 997.08000000000004,
                            Sqft = 15803
                        },
                        new
                        {
                            Id = -69,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(169),
                            Details = "YVGQBFWP JCID",
                            ImageUrl = "",
                            Name = "HNIY Villa",
                            Occupancy = 68,
                            Rate = 573.88999999999999,
                            Sqft = 41433
                        },
                        new
                        {
                            Id = -70,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(184),
                            Details = "ULCZBHRYJXZRCZYM",
                            ImageUrl = "",
                            Name = "ZSHGY Villa",
                            Occupancy = 52,
                            Rate = 366.06999999999999,
                            Sqft = 38552
                        },
                        new
                        {
                            Id = -71,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(200),
                            Details = "QNVAJRV JEBGPZ YU",
                            ImageUrl = "",
                            Name = "YVHSVIO Villa",
                            Occupancy = 48,
                            Rate = 284.82999999999998,
                            Sqft = 25511
                        },
                        new
                        {
                            Id = -72,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(213),
                            Details = "VCKAOMAKNR",
                            ImageUrl = "",
                            Name = "AHHRJR Villa",
                            Occupancy = 28,
                            Rate = 971.26999999999998,
                            Sqft = 22659
                        },
                        new
                        {
                            Id = -73,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(226),
                            Details = "GSSFXMCBRSHDE",
                            ImageUrl = "",
                            Name = "TJXVUKR Villa",
                            Occupancy = 53,
                            Rate = 935.05999999999995,
                            Sqft = 24238
                        },
                        new
                        {
                            Id = -74,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(237),
                            Details = "FTVPXWUVFR",
                            ImageUrl = "",
                            Name = "YY Villa",
                            Occupancy = 56,
                            Rate = 872.57000000000005,
                            Sqft = 10729
                        },
                        new
                        {
                            Id = -75,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(251),
                            Details = "XODJIQDFTDCMCRNAPOQ",
                            ImageUrl = "",
                            Name = "NF Villa",
                            Occupancy = 50,
                            Rate = 717.34000000000003,
                            Sqft = 8926
                        },
                        new
                        {
                            Id = -76,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(264),
                            Details = "DVGHO ITVVX",
                            ImageUrl = "",
                            Name = "OWOQCL Villa",
                            Occupancy = 70,
                            Rate = 844.22000000000003,
                            Sqft = 28968
                        },
                        new
                        {
                            Id = -77,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(280),
                            Details = "DXWOFZWAZDIEVGMMZNO",
                            ImageUrl = "",
                            Name = "SRHKCNX Villa",
                            Occupancy = 4,
                            Rate = 998.46000000000004,
                            Sqft = 7164
                        },
                        new
                        {
                            Id = -78,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(317),
                            Details = "USWRLQXMSP",
                            ImageUrl = "",
                            Name = "GNXRQIP Villa",
                            Occupancy = 9,
                            Rate = 486.79000000000002,
                            Sqft = 27759
                        },
                        new
                        {
                            Id = -79,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(331),
                            Details = " MQYEITQNWVTQGHY",
                            ImageUrl = "",
                            Name = "LIOB Villa",
                            Occupancy = 85,
                            Rate = 324.75,
                            Sqft = 18470
                        },
                        new
                        {
                            Id = -80,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(345),
                            Details = "KNDSULWEIKTFKV",
                            ImageUrl = "",
                            Name = "YRTV Villa",
                            Occupancy = 90,
                            Rate = 718.64999999999998,
                            Sqft = 18088
                        },
                        new
                        {
                            Id = -81,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(358),
                            Details = "UJJKJQUSHR",
                            ImageUrl = "",
                            Name = "FBTWZZ Villa",
                            Occupancy = 29,
                            Rate = 280.0,
                            Sqft = 14252
                        },
                        new
                        {
                            Id = -82,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(372),
                            Details = "OJNIQNFVAQYJQLLJ",
                            ImageUrl = "",
                            Name = "AW Villa",
                            Occupancy = 77,
                            Rate = 921.58000000000004,
                            Sqft = 35845
                        },
                        new
                        {
                            Id = -83,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(388),
                            Details = "BCQRMSHHGTKQQTBCPUA",
                            ImageUrl = "",
                            Name = "XSAXIL Villa",
                            Occupancy = 54,
                            Rate = 391.22000000000003,
                            Sqft = 35749
                        },
                        new
                        {
                            Id = -84,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(403),
                            Details = " IHHSZWCUXWTDAH",
                            ImageUrl = "",
                            Name = "STAK Villa",
                            Occupancy = 33,
                            Rate = 858.00999999999999,
                            Sqft = 8717
                        },
                        new
                        {
                            Id = -85,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(417),
                            Details = "KBIHCK QRHYHVHWF",
                            ImageUrl = "",
                            Name = "NV Villa",
                            Occupancy = 76,
                            Rate = 957.30999999999995,
                            Sqft = 32231
                        },
                        new
                        {
                            Id = -86,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(431),
                            Details = "WB BQTCRUPRQLHAHV",
                            ImageUrl = "",
                            Name = "ZT Villa",
                            Occupancy = 78,
                            Rate = 590.37,
                            Sqft = 43105
                        },
                        new
                        {
                            Id = -87,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(446),
                            Details = "TXDYWFBPGBKC ",
                            ImageUrl = "",
                            Name = "JFOXZI Villa",
                            Occupancy = 62,
                            Rate = 768.09000000000003,
                            Sqft = 5640
                        },
                        new
                        {
                            Id = -88,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(460),
                            Details = "UKRNWVYJCCZV",
                            ImageUrl = "",
                            Name = "LBCNBT Villa",
                            Occupancy = 45,
                            Rate = 463.75,
                            Sqft = 39884
                        },
                        new
                        {
                            Id = -89,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(497),
                            Details = "PEFXRYQIPFA",
                            ImageUrl = "",
                            Name = "BQKCOBA Villa",
                            Occupancy = 22,
                            Rate = 284.62,
                            Sqft = 24398
                        },
                        new
                        {
                            Id = -90,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(513),
                            Details = "DCEDPHGCQPFXKJTXS",
                            ImageUrl = "",
                            Name = "HCZCPUY Villa",
                            Occupancy = 35,
                            Rate = 520.39999999999998,
                            Sqft = 8183
                        },
                        new
                        {
                            Id = -91,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(526),
                            Details = "XKHUPMUQNUYMP",
                            ImageUrl = "",
                            Name = "GAI Villa",
                            Occupancy = 59,
                            Rate = 680.46000000000004,
                            Sqft = 18380
                        },
                        new
                        {
                            Id = -92,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(542),
                            Details = "FHEFEQKSJQQCFFUHRBZ",
                            ImageUrl = "",
                            Name = "QJHD Villa",
                            Occupancy = 35,
                            Rate = 474.07999999999998,
                            Sqft = 45369
                        },
                        new
                        {
                            Id = -93,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(555),
                            Details = "BALFFBECTDFJ ",
                            ImageUrl = "",
                            Name = "LTI Villa",
                            Occupancy = 2,
                            Rate = 848.74000000000001,
                            Sqft = 20471
                        },
                        new
                        {
                            Id = -94,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(569),
                            Details = "KETAKQVWH YBAJY",
                            ImageUrl = "",
                            Name = "RPIZC Villa",
                            Occupancy = 35,
                            Rate = 179.19999999999999,
                            Sqft = 5972
                        },
                        new
                        {
                            Id = -95,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(581),
                            Details = "DKITLZMMQNC",
                            ImageUrl = "",
                            Name = "ZUQ Villa",
                            Occupancy = 32,
                            Rate = 313.58999999999997,
                            Sqft = 15497
                        },
                        new
                        {
                            Id = -96,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(596),
                            Details = "IXHUKGFARTDMSKMLM",
                            ImageUrl = "",
                            Name = "OMF Villa",
                            Occupancy = 85,
                            Rate = 634.83000000000004,
                            Sqft = 37136
                        },
                        new
                        {
                            Id = -97,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(611),
                            Details = "GL A JEMSFBKLF",
                            ImageUrl = "",
                            Name = "SFQCCG Villa",
                            Occupancy = 42,
                            Rate = 524.73000000000002,
                            Sqft = 7649
                        },
                        new
                        {
                            Id = -98,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(626),
                            Details = "DUUHMDVMSPFWOQPW",
                            ImageUrl = "",
                            Name = "IKKY Villa",
                            Occupancy = 58,
                            Rate = 240.28999999999999,
                            Sqft = 45431
                        },
                        new
                        {
                            Id = -99,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 7, 7, 13, 56, 36, 933, DateTimeKind.Local).AddTicks(640),
                            Details = "CZOWMFVDKPMXB",
                            ImageUrl = "",
                            Name = "XNREPI Villa",
                            Occupancy = 94,
                            Rate = 567.80999999999995,
                            Sqft = 7586
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
